name: Build and run unit tests
on: [workflow_dispatch,push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'

        - name: Cache Gradle and wrapper
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-
              
        - name: Make Gradle executable
          run: chmod +x ./gradlew

        - name: Build with Gradle
          uses: gradle/gradle-build-action@v2
          with:
            arguments: test
        - uses: actions/upload-artifact@v3
          if: failure()
          with:
            path: app/build/reports/tests/testDebugUnitTest/index.html
